spring:
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}

openai:
  api-key: ${OPENAI_API_KEY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:8080/curio/api/auth/kakao/callback