spring:
  application:
    name: curio

  profiles:
    active: dev  # 기본은 dev로 지정 (Cloudtype에서는 override 가능)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: curio.notice@gmail.com
    password: hwavgljfeqalxhbw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5d42537aed8e83416f71d42b32ab0cca
            redirect-uri: https://port-0-curio-be-mar0zdvm42447885.sel4.cloudtype.app/curio/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname,account_email

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://port-0-curio-be-mar0zdvm42447885.sel4.cloudtype.app/curio/api/login/oauth2/code/google
            scope: profile,email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  servlet:
    context-path: /curio/api
  port: 8080
  host: 0.0.0.0

openai:
  api-key: ${OPENAI_API_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}

website:
  domain:
    url: http://www.curi-o.site

springdoc:
  api-docs:
    path: /custom-api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
