spring:
  application:
    name: curio

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}  # 기본값 dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: curio.notice@gmail.com
    password: hwavgljfeqalxhbw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /curio/api
  port: 8080
  host: 0.0.0.0

openai:
  api-key: ${OPENAI_API_KEY}

website:
  domain:
    url: http://www.curi-o.site

springdoc:
  api-docs:
    path: /custom-api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
