spring:
  application:
    name: curio

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE} # 기본값 dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: curio.notice@gmail.com
    password: hwavgljfeqalxhbw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  servlet:
    context-path: /curio/api
  port: 8080
  host: 0.0.0.0
  tomcat:
    uri-encoding: UTF-8

openai:
  api-key: ${OPENAI_API_KEY}

website:
  domain:
    url: https://www.curi-o.site

springdoc:
  api-docs:
    path: /custom-api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:8080/curio/api/auth/kakao/callback

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/curio/api/auth/google/callback

frontend:
  redirect-url-local: http://localhost:3000/
  redirect-url-prod: https://curi-o.site/

jwt:
  secret: ${JWT_SECRET}