spring:
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}

openai:
  api-key: ${OPENAI_API_KEY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: https://port-0-curio-be-mar0zdvm42447885.sel4.cloudtype.app/curio/api/auth/kakao/login