spring:
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

openai:
  api-key: ${OPENAI_API_KEY}

frontend:
  redirect-url: http://localhost:3000/


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:8080/curio/api/auth/kakao/callback?env=local

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/curio/api/auth/google/callback

jwt:
  secret: ${JWT_SECRET}